All tha changes have been made.
mrraghur/interviewpreptests pull request #5
Opened 2022-05-17 05:03 UTC by Prashanthveddula

2022-05-18 14:04 UTC, mrraghur commented on May2022/SearchInsertPosition/main.py
> +        print('NO')
We should be able to abstract this code into a method or class and use it for every problem in this project.

2022-05-19 13:34 UTC, Prashanthveddula commented on May2022/ConvertSortedArraytoBST/main.py
> +        arr = [int(x) for x in content]
Added Try expect block for Converted sorted array to bst

2022-05-19 13:34 UTC, Prashanthveddula commented on May2022/ConvertSortedArraytoBST/main.py
> +            self.left = left
created common.py

2022-05-19 13:35 UTC, Prashanthveddula commented on May2022/ConvertSortedArraytoBST/main.py
> +    ans = obj.solutionGold(arr)
This change is also made

2022-05-19 13:35 UTC, Prashanthveddula commented on May2022/RemoveDuplicates/main.py
> +    def soluser(l):
This change is also made

2022-05-19 13:35 UTC, Prashanthveddula commented on May2022/SearchInsertPosition/main.py
> +cp=0
Changed the variable names

2022-05-19 21:20 UTC, mrraghur requested changes

2022-05-19 21:20 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +CountPassed = 0
First letter small and then capital letters whenever required. Search for "camel case" on google.

2022-05-19 21:20 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +    if ans == user_ans:
Why can you move add lines 42 to 47 into common? That way, ALL testcases can use them.

2022-05-19 21:20 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/common.py
> +        self.right = right
This class still needs read from file and write to file.

2022-05-19 21:24 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +        arr = [int(x) for x in content]
This is still not enough. How will I know which file failed? I also wont know reason for the failure if you swallow the exception.

2022-05-19 21:25 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +            self.left = left
Note that common.py must be shared across all python files/problems in the repo. So, you have to move it to a common place, may be make it a child of May2022 directory

2022-05-19 21:25 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +    ans = obj.solutionGold(arr)
good

2022-05-19 21:27 UTC, mrraghur commented on May2022/RemoveElement/main.py
> +        print('YES')
Thanks. But if you realize, this code can be moved into utils.py so that all problems can share it.

2022-05-19 21:27 UTC, mrraghur commented on May2022/ConvertSortedArraytoBST/main.py
> +    if ans == user_ans:
Please do this one.

2022-05-22 18:56 UTC, Prashanthveddula commented on May2022/ConvertSortedArraytoBST/main.py
> +    if ans == user_ans:
Done, its moved to common.py

2022-05-22 18:56 UTC, Prashanthveddula commented on May2022/ConvertSortedArraytoBST/main.py
> +CountPassed = 0
This is also fixed

2022-05-22 18:57 UTC, Prashanthveddula reviewed
All the changes are made

2022-05-22 18:57 UTC, Prashanthveddula commented
All the changes are made

2022-05-25 14:54 UTC, Prashanthveddula commented
Found a way to generate and build bst testcases, In the testcases the -1 value in the txt file represents the 'None' or 'null' value.
Made to changes to main.py such that it can read those None values. Also added a function to comm.py to read the inputs from txt files

2022-05-27 12:38 UTC, merged